import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from "@next/font/google"; // Import Poppins from Google Fonts
import "./globals.css";
import Header from "../components/Header";
import Footer from "@/components/Footer";

// Import existing local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Import Poppins font
const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // Specify the weights you need
  subsets: ["latin"], // Latin subset
  variable: "--font-poppins", // Define a CSS variable for Poppins
  display: "swap", // Optional, improves loading behavior
});

export const metadata: Metadata = {
  title: "FarmIsha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${poppins.variable}  font-poppins bg-white pt-2 sm:pt-6 lg:pt-8 pb-0 px-2 sm:px-12 lg:px-20  overflow-x-hidden`} 
      >
        <Header />
        {children}
        < Footer />
      </body>
    </html>
  );
}
